version: '3.2'

services:
  server-multiuser-table-go:
    container_name: server-multiuser-table-go
    build:
      context: go-server
      args:
        - USER_ID=${USER_ID-1000}
        - GROUP_ID=${GROUP_ID-1000}
    volumes:
      - ../server:/var/www/go/multiuser-table-go/server
    ports:
      - "80:8080"
      - "3456:3456"
      - "2345:2345"
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      multiuser-table-go-net:
        ipv4_address: 172.123.0.4

  db-multiuser-table-go:
    container_name: db-multiuser-table-go
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-multiuser-table-go-db:/var/lib/mysql
      - ./mysql-db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  multiuser-table-go-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.123.0.0/24
    driver_opts:
      com.docker.network.bridge.name: br_mtg

volumes:
  db-multiuser-table-go-db: